# -*- coding: utf-8 -*-
"""email-alarmed-system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLpjAuZElCRiqx00zW-PzjZXQZG1w3EQ
"""

server = smtplib.SMTP_SSL ("smtp.gmail.com", 465)

server.login ("xyz@gmail.com", "password")

server.sendmail("xyz@gmail.com","abc@gmail.com", "Fire emercency project email working configuration")

server.quit()

import smtplib
from email.mime.image import MIMEImage
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import datetime

import ssl
print(ssl.OPENSSL_VERSION)

port = 587  # For starttls
smtp_server = "smtp.gmail.com"
sender_email = input("Type sender email press enter:")
receiver_email = input("Type receiver email press enter:")
password = input("Type your password and press enter:")
message = """\
Subject: FIRE EMERCENCY 

Fire emercency project email working configuration."""

context = ssl.create_default_context()
with smtplib.SMTP(smtp_server, port) as server:
    server.ehlo()  # Can be omitted
    server.starttls(context=context)
    server.ehlo()  # Can be omitted
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message)
    print("Mail Sent")

